import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from 'next/font/google';
// import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300','400','500','600','700','800','900'], // optional weights
  display: 'swap',
  variable: '--font-poppins',
});


export const metadata = {
  title: "Portfolio | Muhammad Shahzil Shahzad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
